### ISSUE TITLE
doesn't respect IClassFixture

### ISSUE THREAD

**Issue by ellisonch** [meziantou/Meziantou.Xunit.ParallelTestFramework#1]
This package seems super cool!  However, I'm having problems using it with my test classes that inherit from `IClassFixture`.  It seems like there are two problems:
* the fixture gets instantiated multiple times per class (it's only supposed to be instantiated once)
* the tests all try to run without waiting for the fixture to finish being instantiated

I would expect that it should instantiate the class fixture, wait for it to finish instantiating, and *then* run all the tests in parallel.

Edit: I'd imagine there's the same problem with `ICollectionFixture`, but I haven't tried it yet.
Edit edit: Ah, it's bad in a different way with `ICollectionFixture`, as grouping things into the same explicit collection is required to use `ICollectionFixture`, but doing so entirely disables parallelization.

My use case: Before any tests can run, I have to set up an external resource that's slow to set up.  Then I want all my tests to share that resource.  I'd basically like to be able to set up that external resource once, then run ALL of my tests in parallel.

**Comment by meziantou** [comment]
This package creates one collection per test to enable parallelization. This has side-effect on icollectionfixture and maybe other things. I'm not sure if it's possible to fix this problem.
If you have one class where you want to disable parallelism, you can create an explicit collection using the "Collection" attribute.
