### ISSUE TITLE
Feature request: Timeout

### ISSUE THREAD

**Issue by programuotojasgf** [meziantou/Meziantou.Xunit.ParallelTestFramework#13]
I want an attribute that gives tests a certain amount of time to complete once they've started.

I've tried writing my own custom TestDiscoverer, but it seems like it's getting overriden by the parralelization test discoverer. Would also be happy to chip in if you have any suggestions on how to work on this.

**Comment by meziantou** [comment]
xunit only supports one `TestFramework`. You can create a new one which wraps both features, or you can fork this project to add your features. Sorry, but this is out of scope for this project.
