### ISSUE TITLE
Snyk found issues !Important!

### ISSUE THREAD

**Issue by NanSigmaBohdanMoroz** [meziantou/Meziantou.Xunit.ParallelTestFramework#14]
![image](https://github.com/meziantou/Meziantou.Xunit.ParallelTestFramework/assets/92790530/2e9a2589-7c1c-4ffb-b998-66b6d3e0def0)

It's critical for us, could you please fix it?
@meziantou  @MatisseHack

**Comment by meziantou** [comment]
I think you can add a direct reference to xunit.extensibility.execution with the latest version to fix the security problem

**Comment by meziantou** [comment]
BTW, the reported vulnerability is on netstandard1.1, which may not be used in your cases (unless you target a non-supported TFM). xunit.extensibility.execution also targets net452 and netstandard2.0, which doesn't contain the vulnerable package.
