### ISSUE TITLE
Duplicate 'Xunit.TestFramework' attribute

### ISSUE THREAD

**Issue by travbeamo** [meziantou/Meziantou.Xunit.ParallelTestFramework#16]
When using both of the following packages:
* Meziantou.Xunit.ParallelTestFramework: Version=2.2.0
* Reqnroll.xUnit: Version=2.0.3

The following error is generated when trying to build project in Visual Studio:
> Duplicate 'Xunit.TestFramework' attribute

Related Xunit Issue: https://github.com/xunit/xunit/issues/2949

**Comment by meziantou** [comment]
You can only declare one `TestFramework` attribute. If you want, you can disable the one generated by this project by setting an msbuild property. But the tests won't run in parallel as the test framework won't be registered.

````
<PropertyGroup>
  <IncludeMeziantouXunitParallelTestFramework>false</IncludeMeziantouXunitParallelTestFramework>
</PropertyGroup>>
````
