### ISSUE TITLE
works too slowly

### ISSUE THREAD

**Issue by brah-mcdude** [meziantou/Meziantou.Xunit.ParallelTestFramework#18]
i installed this package in my solution. all tests passed before installation. 
after install, half failed. but if i ran each one then it passed. 
each test fail was due to timeout. 
i'm building an akka.net based system. 
https://github.com/akkadotnet/akka.net
i decided to remove the package. 
are tests suppose to run slower with this package? 
am i missing something? 
i just installed the package and ran all tests. 
should i have added some code?

**Comment by meziantou** [comment]
All tests start immediately. Then, the xUnit's SynchronizationContext handles the max parallelism (at async/await level, not per test). So, a test can start first, be _blocked_ by the synchronization context, and finish last.

**Comment by brah-mcdude** [comment]
i added the following line at the start of each test
```c#
        await Task.Delay(1);
```
but still half the tests are failing with timeout.
:(

**Comment by meziantou** [comment]
Adding this line shouldn't change anything. If you have max 2 threads and 4 tests, the execution can be:

````
Thread 1: | Test1 (a long synchronous test)               |
Thread 2: | Test2 | Test3 | Test5 | Test4 | Test2 | Test6 |
````

You can see that Test2 is scheduled multiple times as it may have multiple continuations. 
But there is no order guarantee, so it can run differently.

I don't know how you configure the timeout in your application. But, when a test starts, you don't control when the code will actually run. So, if you have a CancellationToken with a short delay, there are lots of chances that it will expire before the test ends.
