### ISSUE TITLE
ClassData/MemberData not being parallelized if reference type is being yielded

### ISSUE THREAD

**Issue by aomader** [meziantou/Meziantou.Xunit.ParallelTestFramework#8]
I do not know whether there is a specific reason for that, but as soon as a theory's data contains reference types (i.e., class objects), the theory is not run in parallel, but sequentially.

Consider for example the following two tests:

```cs
public class Test
{
    [Theory]
    [ClassData(typeof(TestInts))]
    public Task DoesRunInParallel(int i) => Task.Delay(2000);

    [Theory]
    [ClassData(typeof(TestObjs))]
    public Task DoesNotRunInParallel(Obj o) => Task.Delay(2000);
}

public class TestInts : TheoryData<int>
{
    public TestInts()
    {
        Add(1);
        Add(1);
        Add(1);
        Add(1);
        Add(1);
    }
}

public class Obj {}

public class TestObjs : TheoryData<Obj>
{
    public TestObjs()
    {
        Add(new Obj());
        Add(new Obj());
        Add(new Obj());
        Add(new Obj());
        Add(new Obj());
    }
}
```

The test `DoesRunInParallel` in fact does run in parallel, as advertised. However, the test `DoesNotRunInParallel` is run sequentially, while the only difference between those two is that the latter test's data yields a reference type (`Obj`).

Is there specific reason why that is?

**Comment by aomader** [comment]
Turns out the `IXunitSerializable` is necessary for that on the data.

**Comment by cmeeren** [comment]
This is not (just) about value vs. reference types. I have a custom `struct` that also has this behavior.

Furthermore, when investigating `IXunitSerializable`, it seems that it's mostly used to make xUnit report multiple test cases instead of just a single test case. However, in my case, xUnit successfully reports multiple test cases even without having to implement `IXunitSerializable`. So I'm not sure why the tests are not parallel, too.

Is there any reason why this framework should require `IXunitSerializable` for parallelization, when xUnit does not seem to require it to report each of the test cases separately?

**Comment by meziantou** [comment]
@cmeeren Can you provide a simple repro?

**Comment by meziantou** [comment]
xunit exposes only one test when the struct doesn't implement `IXunitSerializable. This test run all test cases sequentially. So, the ParallelTestFramework cannot parallelize test cases as it is not aware of all cases.

**Comment by cmeeren** [comment]
I see. Then the fact that I see multiple test cases in Rider is something that Rider detects itself.

**Comment by meziantou** [comment]
Rider/VS can have their own logic to detect tests. The idea is to avoid using the test protocol, which requires to build the code, to speed up the UI when they can detect tests from the code.

I wonder if Rider is able to run a single test case, as it doesn't seem to be supported by xUnit.

**Comment by cmeeren** [comment]
> I wonder if Rider is able to run a single test case, as it doesn't seem to be supported by xUnit.

Yes, I can confirm that this works (regardless of whether or not the data is serializable).
